# Generated by Django 4.2.1 on 2023-05-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task", old_name="completd", new_name="completed",
        ),
    ]
